### ISSUE TITLE
Unable to export to evernote, until set allows_multiple_exports() = true

### ISSUE THREAD

**Issue by nadavkav** [thatsvishalhere/moodle-portfolio_evernote#1]
Evernote portfolio was not listed under the available export portfolio plugins, while trying to export a file I uploaded to an assignment activity.

set allows_multiple_exports() = true, worked around this problem.
And the file was successfully exported.

I was using a sandbox account.

I am using Moodle 2.4

**Comment by thatsvishalhere** [comment]
I'm so sorry, I didn't notice this issue mentioned by you before. I'll look into the issue and let you know. Thanks for reporting the issue!

**Comment by nadavkav** [comment]
No worries :-)
It happens to me too. Take your time :-)

**Comment by thatsvishalhere** [comment]
@nadavkav :+1: I guess the allow_multiple_exports() was working well on sandbox evernote, but not on production servers. I've changed the values and its working well right now. Thanks again for reporting this! :)

**Comment by nadavkav** [comment]
Great :smile:

**Comment by nadavkav** [comment]
Closing...
